### ISSUE TITLE
リポジトリのソースを見て気になったところ

### ISSUE THREAD

**Issue by takezoe** [shige0808/docotsubu#2]
## リポジトリに不要なファイルが入っている

.projectやtargetディレクトリがリポジトリに入ってしまっているので消しましょう。繰り返しになりますが、リポジトリに入れたくないものは.gitignoreに追加しておきましょう（前作ったと思うんですがいつの間にか消えている）。

今の状態だとこんな感じの.gitignoreを作成しておけばよいはず

```
target/
bin/
.project
.classpath
.settings
```

また、PostgreSQLのjarファイルもPostgreSQLを使い始めるまで不要です

いろいろやると動かなくなった時の切り分けが面倒になるのでいったん消してしまいましょう

## JSP内のパス

JSP内のリンクやフォームに記述されているパスですが、

```jsp
<a href="/">戻る</a>
<a href="/Logout">ログアウト</a>
```

などのようになっているところがローカルとHeroku上でパスがずれてしまうと思うのですが、以下のように `${pageContext.request.contextPath}` を使うとぞれぞれの環境でのパスを出力することができます。

```jsp
<a href="${pageContext.request.contextPath}/">戻る</a>
<a href="${pageContext.request.contextPath}/Logout">ログアウト</a>
```

**Comment by shige0808** [comment]
ありがとうございます。対応しました
